# inbuilt
import logging

# external
from pyspark.sql import SparkSession
from delta.tables import DeltaTable

# internal
from handuflow.data_movement_controller.audit_columns import (
    AuditColumns,
    CDC_STREAM_COLUMN,
    TargetLoadKind,
)
from handuflow.data_movement_controller.data_class.load_result import LoadResult
from handuflow.data_movement_controller.data_class.load_config import LoadConfig
from handuflow.data_movement_controller.base_load_strategy import BaseLoadStrategy
from handuflow.data_movement_controller.load_integrity import LoadIntegrityVerifier
from handuflow.exception.data_load_exception import DataLoadException


class SCDType2(BaseLoadStrategy):

    def __init__(self, config: LoadConfig, spark: SparkSession) -> None:
        super().__init__(config=config, spark=spark)
        self.logger = logging.getLogger(__name__)
        self.logger.info("Initializing SCD_TYPE_2 data transfer component...")

    def __supports_identity(self) -> bool:
        return "databricks" in self.spark.version.lower()

    def load(self):
        try:
            self._enforce_load_type_consistency()
            if not self._create_staging_layer():
                self.logger.warning(
                    "SCD Type-2 skipped: no staging changes detected."
                )
                return LoadResult(
                    feed_id=self.config.master_specs["feed_id"],
                    success=True,
                    skipped=True,
                    total_rows_inserted=0,
                    total_rows_deleted=0,
                    total_rows_updated=0,
                )

            target_table = self._current_target_table_name
            try:
                all_keys = LoadIntegrityVerifier.require_primary_keys(
                    self.config.feed_specs, target_table
                )
            except DataLoadException:
                return LoadResult(
                    feed_id=self.config.master_specs["feed_id"],
                    success=False,
                    total_rows_inserted=0,
                    total_rows_deleted=0,
                    total_rows_updated=0,
                )

            incr_df = AuditColumns.prepare_scd_stream(
                self._current_staging_incremental_table_df,
                self.config.feed_specs,
                all_keys,
            )
            if incr_df.count() == 0:
                self.logger.warning("No CDC changes for SCD-2 on %s.", target_table)
                return LoadResult(
                    feed_id=self.config.master_specs["feed_id"],
                    success=False,
                    skipped=True,
                    total_rows_inserted=0,
                    total_rows_deleted=0,
                    total_rows_updated=0,
                )

            if self.spark.catalog.tableExists(target_table):
                if self._rebuild_target_partition_layout(
                    target_table,
                    self.spark.table(target_table),
                    load_type="SCD_TYPE_2",
                ):
                    active_rows = (
                        self.spark.table(target_table)
                        .filter("_x_is_active = 1")
                        .count()
                    )
                    self._post_load_verify(minimum_row_count=1)
                    self.logger.info(
                        "SCD-2 partition rebuild complete (%s active rows).",
                        active_rows,
                    )
                    return LoadResult(
                        feed_id=self.config.master_specs["feed_id"],
                        success=True,
                        total_rows_inserted=active_rows,
                        total_rows_deleted=0,
                        total_rows_updated=0,
                    )

            if not self.spark.catalog.tableExists(target_table):
                self.logger.info("Creating SCD-2 target table %s.", target_table)
                write_df = AuditColumns.scd_business_subset_enforced(
                    incr_df, self.config.feed_specs
                ).drop(CDC_STREAM_COLUMN)
                schema_cols = [
                    f"{field.name} {field.dataType.simpleString()}"
                    for field in write_df.schema
                    if field.name != CDC_STREAM_COLUMN
                ]
                surrogate = (
                    "_x_surrogate_key BIGINT GENERATED BY DEFAULT AS IDENTITY"
                    if self.__supports_identity()
                    else "_x_surrogate_key BIGINT"
                )
                partition_clause = ""
                keys = self._partition_keys()
                if keys:
                    write_df = self._prepare_partition_columns(write_df)
                    self._validate_partition_columns_not_null(write_df)
                    partition_clause = (
                        f" PARTITIONED BY ({', '.join(keys)})"
                    )
                ddl = f"""
                CREATE TABLE {target_table} (
                    {surrogate},
                    {", ".join(schema_cols)}
                ) USING DELTA{partition_clause}
                """
                self.spark.sql(ddl)
                self._write_delta_table(
                    write_df,
                    target_table,
                    mode="append",
                )
                inserted = self.spark.table(target_table).count()
                self._post_load_verify(minimum_row_count=inserted)
                return LoadResult(
                    feed_id=self.config.master_specs["feed_id"],
                    success=True,
                    total_rows_inserted=inserted,
                    total_rows_deleted=0,
                    total_rows_updated=0,
                )

            AuditColumns.assert_target_schema(
                self.spark,
                target_table,
                self.config.feed_specs,
                TargetLoadKind.SCD_TYPE_2,
            )

            target = DeltaTable.forName(self.spark, target_table)
            key_cond = " AND ".join([f"t.{k} = s.{k}" for k in all_keys])
            close_cond = (
                f"{key_cond} AND t._x_is_active = 1 AND ("
                f"t._x_row_hash <> s._x_row_hash OR s._x_operation = 'delete'"
                ")"
            )
            (
                target.alias("t")
                .merge(incr_df.alias("s"), close_cond)
                .whenMatchedUpdate(
                    set={
                        "_x_is_active": "0",
                        "_x_date_to": "current_timestamp()",
                        "_x_last_modification_timestamp": "current_timestamp()",
                        "_x_last_operation": "s._x_operation",
                    }
                )
                .execute()
            )
            insert_on = (
                f"{key_cond} AND t._x_is_active = 1 AND t._x_row_hash = s._x_row_hash"
            )
            insert_df = AuditColumns.scd_business_subset_enforced(
                incr_df, self.config.feed_specs
            )
            scd_insert_cols = [
                c
                for c in insert_df.columns
                if c not in (CDC_STREAM_COLUMN, "_x_commit_version", "_x_commit_timestamp")
            ]
            (
                target.alias("t")
                .merge(insert_df.alias("s"), insert_on)
                .whenNotMatchedInsert(
                    condition=f"s.{CDC_STREAM_COLUMN} != 'delete'",
                    values={c: f"s.{c}" for c in scd_insert_cols},
                )
                .execute()
            )
            self.spark.sql(
                f"ALTER TABLE {target_table} "
                f"SET TBLPROPERTIES ('data.load_type' = "
                f"'{self.config.master_specs['load_type']}')"
            )
            active_rows = (
                self.spark.table(target_table).filter("_x_is_active = 1").count()
            )
            self._post_load_verify(minimum_row_count=1)
            self.logger.info("SCD-2 load completed: %s", target_table)
            return LoadResult(
                feed_id=self.config.master_specs["feed_id"],
                success=True,
                total_rows_inserted=active_rows,
                total_rows_deleted=0,
                total_rows_updated=0,
            )
        except Exception as e:
            raise DataLoadException(
                original_exception=e,
                message=f"Error during SCD_TYPE_2 for {self._current_target_table_name}: {e}",
                error_code="HF043",
            )
